### ISSUE TITLE
wozmon fails

### ISSUE THREAD

**Issue by polluks** [davidly/ntvao#2]
I have to reset the terminal after this error message
```
$ ./ntvao wozmon.hex
\
R
mos6502 unsupported comparison instruction 33

**Comment by davidly** [comment]
Thanks for reporting this. Yes, the terminal session isn't restored on hard failures. R without an address argument runs whatever random values are in RAM. When the emulator exits it should restore the console to its original state.

**Comment by davidly** [comment]
OK, I added a fix to reset the terminal on fatal errors.
